version: '3.8'

services:
  currency-exchange-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - API_BASE_URL=https://jsonplaceholder.typicode.com
      - API_TIMEOUT_SECONDS=30
      - API_RETRY_COUNT=3
      - API_RETRY_DELAY_SECONDS=1
      - EXCHANGE_RATE_API_BASE_URL=https://open.er-api.com/v6/latest
      - EXCHANGE_RATE_API_KEY=
      - OPEN_EXCHANGE_RATES_BASE_URL=https://openexchangerates.org/api/latest.json
      - OPEN_EXCHANGE_RATES_API_KEY=
      - FRANKFURTER_API_BASE_URL=https://api.frankfurter.app/latest
      - EXCHANGE_RATE_HOST_BASE_URL=https://api.exchangerate.host/latest
      - RATES_CACHE_TTL_SECONDS=60
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60
      - RATE_LIMIT_BURST=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - currency-exchange-network

networks:
  currency-exchange-network:
    driver: bridge



